version: '3.8'

services:
  db:
    image: postgres:15-alpine
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    deploy:
      placement:
        constraints:
          - node.role == manager # Базу данных лучше держать на конкретном узле для стабильности данных
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-postgres} -d $${POSTGRES_DB:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    env_file: .env
    volumes:
      - redis_data:/data
    deploy:
      replicas: 1

  rabbitmq:
    image: rabbitmq:3-management-alpine
    env_file: .env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl -q status || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 5

  backend:
    image: ghcr.io/h00yaday/charnik_online/backend:latest
    env_file: .env
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
      restart_policy:
        condition: on-failure

  frontend:
    image: ghcr.io/h00yaday/charnik_online/frontend:latest
    env_file: .env
    deploy:
      replicas: 1

  celery_worker:
    image: ghcr.io/h00yaday/charnik_online/backend:latest
    command: celery -A core.celery_app.celery_app worker --loglevel=info
    env_file: .env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  caddy:
    image: caddy:alpine
    ports:
      - "80:80"
      - "443:443"
    env_file: .env
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    deploy:
      placement:
        constraints:
          - node.role == manager


volumes:
  pgdata:
    external: true
    name: charnik_online_pgdata
  caddy_data:
    external: true
    name: charnik_online_caddy_data
  caddy_config:
    external: true
    name: charnik_online_caddy_config
  redis_data:
    external: true
    name: charnik_online_redis_data
  rabbitmq_data:
    external: true
    name: charnik_online_rabbitmq_data