"""add email to user

Revision ID: 285f7a762bd6
Revises: c1e8f35a7b8f
Create Date: 2026-04-26 11:56:27.058000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '285f7a762bd6'
down_revision: Union[str, None] = 'c1e8f35a7b8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attacks_character_id'), table_name='attacks')
    op.drop_index(op.f('ix_characters_owner_id'), table_name='characters')
    op.drop_index(op.f('ix_features_character_id'), table_name='features')
    op.drop_index(op.f('ix_spells_character_id'), table_name='spells')
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    op.create_index(op.f('ix_spells_character_id'), 'spells', ['character_id'], unique=False)
    op.create_index(op.f('ix_features_character_id'), 'features', ['character_id'], unique=False)
    op.create_index(op.f('ix_characters_owner_id'), 'characters', ['owner_id'], unique=False)
    op.create_index(op.f('ix_attacks_character_id'), 'attacks', ['character_id'], unique=False)
    # ### end Alembic commands ###
