"""add cast fields to spell model

Revision ID: 2f0bc38c78a2
Revises: 637999f90793
Create Date: 2026-03-22 07:46:22.930042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f0bc38c78a2'
down_revision: Union[str, None] = '637999f90793'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spells', sa.Column('requires_attack_roll', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('spells', sa.Column('spell_attack_bonus', sa.Integer(), server_default='0', nullable=False))
    op.add_column('spells', sa.Column('damage_dice', sa.String(length=20), nullable=True))
    op.add_column('spells', sa.Column('damage_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spells', 'damage_type')
    op.drop_column('spells', 'damage_dice')
    op.drop_column('spells', 'spell_attack_bonus')
    op.drop_column('spells', 'requires_attack_roll')
    # ### end Alembic commands ###
