"""make character full sheet final fix

Revision ID: 637999f90793
Revises: 1b55d1b5daa3
Create Date: 2026-03-21 17:20:16.804604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '637999f90793'
down_revision: Union[str, None] = '1b55d1b5daa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_features_id'), 'features', ['id'], unique=False)
    op.add_column('characters', sa.Column('race', sa.String(length=50), server_default='Человек', nullable=False))
    op.add_column('characters', sa.Column('character_class', sa.String(length=50), server_default='Воин', nullable=False))
    op.add_column('characters', sa.Column('subclass', sa.String(length=50), nullable=True))
    op.add_column('characters', sa.Column('background', sa.String(length=50), nullable=True))
    op.add_column('characters', sa.Column('saving_throws', sa.JSON(), server_default='{}', nullable=False))
    op.add_column('characters', sa.Column('speed', sa.Integer(), server_default='30', nullable=False))
    op.add_column('characters', sa.Column('initiative_bonus', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'initiative_bonus')
    op.drop_column('characters', 'speed')
    op.drop_column('characters', 'saving_throws')
    op.drop_column('characters', 'background')
    op.drop_column('characters', 'subclass')
    op.drop_column('characters', 'character_class')
    op.drop_column('characters', 'race')
    op.drop_index(op.f('ix_features_id'), table_name='features')
    op.drop_table('features')
    # ### end Alembic commands ###
