"""add modifiers to features

Revision ID: 84dd276cc5a0
Revises: 92db9651a5da
Create Date: 2026-03-30 08:12:12.570002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84dd276cc5a0'
down_revision: Union[str, None] = '92db9651a5da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('features', sa.Column('modifiers', sa.JSON(), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('features', 'modifiers')
    # ### end Alembic commands ###
