name: Deploy to Docker Swarm

on:
  push:
    branches: [ main ]

jobs:
  # === ШАГ 1: Сборка и отправка образов в GitHub Packages ===
  build-and-push:
    runs-on: ubuntu-latest
    env:                   
      REPO_LOWER: ""
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      # Переводим название репозитория в нижний регистр для Docker
      - name: Lowercase repo name
        run: echo "REPO_LOWER=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend_api
          push: true
          tags: ghcr.io/${{ env.REPO_LOWER }}/backend:latest #ignore

      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend_app
          push: true
          tags: ghcr.io/${{ env.REPO_LOWER }}/frontend:latest # ignore

  deploy:
    needs: build-and-push # Ждем, пока образы соберутся
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Swarm via SSH
        uses: appleboy/ssh-action@v1.0.3
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          DATABASE_URL: "postgresql+asyncpg://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@${{ secrets.POSTGRES_HOST }}:${{ secrets.POSTGRES_PORT }}/${{ secrets.POSTGRES_DB }}"
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          DB_ECHO: ${{ secrets.DB_ECHO }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ALGORITHM: ${{ secrets.ALGORITHM }}
          ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }} 
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          REDIS_URL: "redis://${{ secrets.REDIS_HOST }}:${{ secrets.REDIS_PORT }}"
          CELERY_BROKER_URL: "amqp://guest:guest@rabbitmq:5672//"
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          MAIL_FROM: ${{ secrets.MAIL_FROM }}
          MAIL_PORT: ${{ secrets.MAIL_PORT }}
          MAIL_SERVER: ${{ secrets.MAIL_SERVER }}
          MAIL_FROM_NAME: ${{ secrets.MAIL_FROM_NAME }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: POSTGRES_USER,POSTGRES_PASSWORD,POSTGRES_DB,DATABASE_URL,POSTGRES_HOST,POSTGRES_PORT,DB_ECHO,SECRET_KEY,ALGORITHM,ACCESS_TOKEN_EXPIRE_MINUTES,ENVIRONMENT,VITE_API_URL,DOMAIN_NAME,REDIS_HOST,REDIS_PORT,REDIS_URL,CELERY_BROKER_URL,MAIL_USERNAME,MAIL_PASSWORD,MAIL_FROM,MAIL_PORT,MAIL_SERVER,MAIL_FROM_NAME
          script: |
            cd /home/ubuntu/charnik_online
            git fetch origin main
            git reset --hard origin/main
            
            # Собираем .env файл
            echo "POSTGRES_USER=$POSTGRES_USER" > .env
            echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> .env
            echo "POSTGRES_DB=$POSTGRES_DB" >> .env
            echo "POSTGRES_HOST=$POSTGRES_HOST" >> .env
            echo "POSTGRES_PORT=$POSTGRES_PORT" >> .env
            echo "DATABASE_URL=$DATABASE_URL" >> .env
            echo "SECRET_KEY=$SECRET_KEY" >> .env
            echo "ENVIRONMENT=$ENVIRONMENT" >> .env
            echo "ACCESS_TOKEN_EXPIRE_MINUTES=$ACCESS_TOKEN_EXPIRE_MINUTES" >> .env
            echo "ALGORITHM=$ALGORITHM" >> .env
            echo "DB_ECHO=$DB_ECHO" >> .env
            echo "VITE_API_URL=$VITE_API_URL" >> .env
            echo "DOMAIN_NAME=$DOMAIN_NAME" >> .env
            echo "REDIS_HOST=$REDIS_HOST" >> .env
            echo "REDIS_PORT=$REDIS_PORT" >> .env
            echo "REDIS_URL=$REDIS_URL" >> .env
            echo "CELERY_BROKER_URL=$CELERY_BROKER_URL" >> .env
            echo "MAIL_USERNAME=$MAIL_USERNAME" >> .env
            echo "MAIL_PASSWORD=$MAIL_PASSWORD" >> .env
            echo "MAIL_FROM=$MAIL_FROM" >> .env
            echo "MAIL_PORT=$MAIL_PORT" >> .env
            echo "MAIL_SERVER=$MAIL_SERVER" >> .env
            echo "MAIL_FROM_NAME=$MAIL_FROM_NAME" >> .env
            
            echo "${{ secrets.GITHUB_TOKEN }}" | sudo docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            sudo docker compose down --remove-orphans || true
            
            sudo docker stack deploy -c docker-compose.swarm.yml dnd_app --with-registry-auth