name: Deploy to AWS EC2

on:
  push:
    branches:
      - main 
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        
      - name: Run Ruff Linter
        run: uvx ruff check backend_api/
        
      - name: Run Ruff Formatter check
        run: uvx ruff format --check backend_api/
        
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        env:
          REPO_URL: "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
          # === DATABASE ===
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          DATABASE_URL: "postgresql+asyncpg://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@${{ secrets.POSTGRES_HOST }}:${{ secrets.POSTGRES_PORT }}/${{ secrets.POSTGRES_DB }}"
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          DB_ECHO: ${{ secrets.DB_ECHO }}

          # === FastAPI ===
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ALGORITHM: ${{ secrets.ALGORITHM }}
          ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}

          # === Frontend ===
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }} 

          # === Redis ===
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          REDIS_URL: "redis://${{ secrets.REDIS_HOST }}:${{ secrets.REDIS_PORT }}"

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: POSTGRES_USER,POSTGRES_PASSWORD,POSTGRES_DB,DATABASE_URL,POSTGRES_HOST,POSTGRES_PORT,DB_ECHO,SECRET_KEY,ALGORITHM,ACCESS_TOKEN_EXPIRE_MINUTES,ENVIRONMENT,VITE_API_URL,DOMAIN_NAME,REDIS_HOST,REDIS_PORT,REDIS_URL
          script: |
            cd /home/ubuntu
            
            if [ ! -d "charnik_online" ]; then
              git clone $REPO_URL charnik_online
            fi
            
            cd charnik_online
            git fetch origin main
            git reset --hard origin/main
            
            # Собираем полный файл .env
            
            # === DATABASE ===
            echo "POSTGRES_USER=$POSTGRES_USER" > .env
            echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> .env
            echo "POSTGRES_DB=$POSTGRES_DB" >> .env
            echo "POSTGRES_HOST=$POSTGRES_HOST" >> .env
            echo "POSTGRES_PORT=$POSTGRES_PORT" >> .env
            echo "DATABASE_URL=$DATABASE_URL" >> .env

            # === FastAPI ===
            echo "SECRET_KEY=$SECRET_KEY" >> .env
            echo "ENVIRONMENT=$ENVIRONMENT" >> .env
            echo "ACCESS_TOKEN_EXPIRE_MINUTES=$ACCESS_TOKEN_EXPIRE_MINUTES" >> .env
            echo "ALGORITHM=$ALGORITHM" >> .env
            echo "DB_ECHO=$DB_ECHO" >> .env

            # === Frontend ===
            echo "VITE_API_URL=$VITE_API_URL" >> .env
            echo "DOMAIN_NAME=$DOMAIN_NAME" >> .env
            # === Redis ===
            echo "REDIS_HOST=$REDIS_HOST" >> .env
            echo "REDIS_PORT=$REDIS_PORT" >> .env
            echo "REDIS_URL=$REDIS_URL" >> .env
            
            # Удаляем предыдущие контейнеры и запускаем новые
            sudo docker-compose down --remove-orphans
            sudo docker-compose up -d --build --remove-orphans